// BestieVerse - Compliments, Facts, and Fortunes Database

export const complimentsList = [
  "You make conversations fun without even trying.",
  "You always know how to make people smile when they need it.",
  "Your energy is unmatched.",
  "You somehow make ordinary moments memorable.",
  "You're cooler than a secure high-speed WiFi connection. 📶",
  "You are impossible to replace. Seriously.",
  "If being awesome was a crime, you'd be serving a life sentence.",
  "Your laugh is my absolute favorite sound. 🎙️",
  "You are a rare gem in a world full of pebbles. 💎",
  "You make the bad days feel totally manageable.",
  "You're the kind of friend people write books about.",
  "The world is 100 times better just because you're in it.",
  "You have the best style, even in your pajamas. 💅",
  "Your energy is infectious and incredibly uplifting.",
  "You are strong, resilient, and totally capable of anything.",
  "I'm so lucky to have you as my partner-in-crime.",
  "You're like the peanut butter to my jelly.",
  "You notice when people are feeling down without them saying a word.",
  "You don't take yourself too seriously, and it's awesome.",
  "You have an amazing capacity for caring about people.",
  "You deserve unlimited happiness and all the snacks in the world. 🍩",
  "You listen to my endless dramatics without complaining.",
  "You always send the funniest memes at the exact right moment.",
  "You never judge me for my weird habits or terrible jokes.",
  "You are genuinely kind to everyone you meet.",
  "Your laugh makes everyone else want to laugh along.",
  "You tell the absolute truth when I need to hear it.",
  "You remember the tiniest details about our conversations.",
  "You support my crazy ideas, no matter how wild.",
  "You have the best advice (even if we both ignore it).",
  "You forgive easily and keep no grudges.",
  "You make the absolute best reactions to gossip.",
  "You're always ready to eat food with me.",
  "You are passionate about the things you love.",
  "You make me feel safe to be my 100% weird self.",
  "You stand up for the people you care about.",
  "You celebrate my small wins as if they were giant victories.",
  "You bring positive vibes wherever you go.",
  "You can turn any awkward situation into a hilarious story.",
  "You hold onto memories so warmly.",
  "You never fail to text back when it's an emergency.",
  "You give the absolute best high-fives. 🖐️",
  "You are open-minded and willing to try new things.",
  "You make me laugh when I want to cry.",
  "You are a great listener.",
  "You are determined and don't give up easily.",
  "You look great even when you just woke up.",
  "You keep all my secrets locked in a vault. 🔒",
  "You are independent and strong-willed.",
  "You are highly empathetic and feel deeply.",
  "You are the ultimate comfort person.",
  "You don't care about shallow things; you look at the heart.",
  "You make me want to be a better person.",
  "You have a beautiful vibe that attracts good things.",
  "You are so easy to talk to.",
  "You appreciate the simple things in life.",
  "You have a cute way of pronouncing certain words.",
  "You are always down for a cozy movie night.",
  "You are honest about your feelings.",
  "You are my absolute favorite notification to see.",
  "You are incredibly loyal.",
  "You make the best screenshots of our funny typos.",
  "You have a heart that feels for others' pain.",
  "You are a fantastic companion for doing absolutely nothing.",
  "You treat my family like your own.",
  "You are a source of endless inspiration.",
  "You appreciate my efforts and always say thank you.",
  "You never forget my birthday.",
  "You are a ray of light in dark times.",
  "You make the best tea/coffee sessions.",
  "You are always there to cheer me up.",
  "You are sweet even when you try to be mean.",
  "You are a gift to everyone who knows you.",
  "You never let me walk alone in the dark.",
  "You handle my mood swings with grace.",
  "You are the anchor in my chaotic life.",
  "You are simply, undeniably, the best friend ever.",
  "You make the world feel a little bit smaller and safer.",
  "Your memes are 10/10 level. Certified expert.",
  "You make me feel heard and understood.",
  "You have a beautiful heart.",
  "You are cooler than any secret password.",
  "You have a great taste in music and movies.",
  "You are incredibly humble about how awesome you are.",
  "You are protective of your friends.",
  "You believe in the good in people.",
  "You have a bright and bubbly personality.",
  "You have a beautiful smile that lights up the room.",
  "You notice when I'm quiet and check up on me.",
  "You make ordinary activities feel like a mini road trip.",
  "You are the sister/brother I got to choose.",
  "You are always honest with me.",
  "You are a masterpiece in progress.",
  "You are the best gossip partner in the universe.",
  "You don't judge me when I order too much food.",
  "You are the first person I want to text when something happens.",
  "Your existence makes my life so much happier. ❤️"
];

export const factsList = {
  friendship: [
    "Studies show that having close friends increases life expectancy and reduces stress.",
    "Animals like cows, horses, and elephants form close lifelong best friendships.",
    "Psychologists believe that friendships formed in college or school are highly resilient.",
    "Sending memes to friends is a modern form of social grooming, similar to chimpanzees grooming each other.",
    "The word 'friend' comes from the Old English 'freond,' which means 'to love.'"
  ],
  animal: [
    "Sea otters hold hands while sleeping so they don't drift apart. 🦦",
    "Cows have best friends and get stressed when they are separated from them. 🐄",
    "Male puppies will often let female puppies 'win' in play fights to keep playing.",
    "Gentoo penguins propose to their lifemate with a carefully chosen pebble. 🐧",
    "Cats make about 100 different sounds, while dogs only make about 10."
  ],
  space: [
    "One day on Venus is longer than one year on Venus. 🪐",
    "Footprints left by astronauts on the moon will last for at least 100 million years.",
    "Neutron stars are so dense that a single teaspoon of their material would weigh billions of tons.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "Space smells like a mixture of hot metal, seared steak, and welding fumes."
  ],
  technology: [
    "The first computer mouse was invented in 1964 and was made of wood. 🪵🖱️",
    "About 90% of the world's currency exists only on computers as digital entries.",
    "The original name for search engine Google was 'Backrub.'",
    "The first text message ever sent said 'Merry Christmas.' 🎄",
    "Over 4 billion people around the world now use a smartphone."
  ],
  food: [
    "Honey never spoils. You can eat 3000-year-old Egyptian tomb honey safely. 🍯",
    "Pineapples take almost three years to grow and mature from a single seed.",
    "Apples float in water because they are 25% air. 🍎",
    "The world's most expensive spice is saffron, which is harvested by hand.",
    "Chocolate was once used as currency by the ancient Aztecs."
  ],
  history: [
    "Ancient Romans used diluted urine as mouthwash because of the ammonia. 🦷",
    "The Great Pyramid of Giza was built before woolly mammoths went extinct.",
    "Albert Einstein was offered the presidency of Israel in 1952 but declined.",
    "The shortest war in history lasted only 38 minutes, between Britain and Zanzibar.",
    "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid."
  ]
};

export const fortunesList = [
  "Today you'll discover an amazing song that will repeat in your head. 🎧",
  "You'll laugh at something completely random and struggle to stop. 😂",
  "Someone will send you a funny reel that will make you smile.",
  "An unexpected snack is in your near future. Eat it with joy! 🍕",
  "You will find money in a pocket you forgot about. 🪙",
  "A highly dramatic text exchange will keep you entertained today.",
  "Your luck today is 100% higher if you drink a glass of water right now.",
  "Today is the perfect day to ignore your problems and take a 2-hour nap. 😴",
  "You will cross paths with a very cute animal or animal video today.",
  "Someone is thinking about you right now and smiling. (Hint: It's me!)",
  "You will successfully avoid an awkward conversation today. Success!",
  "A wave of creativity will hit you, probably right before you sleep.",
  "Your future holds a lot of laughter, some good food, and zero toxic drama.",
  "Today's tip: Do not overthink that text message. Just hit send!",
  "A cozy blanket and a movie are calling your name for this weekend. 🍿"
];
