// BestieVerse - Joke Database (100+ high-quality puns, dad jokes, and laughs)

export const jokesList = [
  { q: "Why did the scarecrow win an award?", a: "Because he was outstanding in his field! 🌾" },
  { q: "What do you call a fake noodle?", a: "An impasta! 🍝" },
  { q: "Why don't scientists trust atoms?", a: "Because they make up everything! ⚛️" },
  { q: "Why did the picture go to jail?", a: "Because it was framed! 🖼️" },
  { q: "What do you call a sleeping dinosaur?", a: "A dino-snore! 🦖" },
  { q: "Why can't a nose be 12 inches long?", a: "Because then it would be a foot! 👃" },
  { q: "What do you call cheese that isn't yours?", a: "Nacho cheese! 🧀" },
  { q: "Why did the bicycle collapse?", a: "Because it was two-tired! 🚲" },
  { q: "How do you organize a space party?", a: "You planet! 🪐" },
  { q: "Why did the tomato blush?", a: "Because it saw the salad dressing! 🍅" },
  { q: "What do you call a dog that can do magic tricks?", a: "A Labracadabrador! 🪄🐕" },
  { q: "Why did the math book look sad?", a: "Because it had too many problems! 📐" },
  { q: "What do you call a belt with a clock on it?", a: "A waist of time! ⏳" },
  { q: "Why do we tell actors to 'break a leg'?", a: "Because every play has a cast! 🎭" },
  { q: "What do you call a group of killer wells?", a: "An killer whale-group! (Or just an orchestra!) 🐳" },
  { q: "Why did the strawberry cry?", a: "Because its parents were in a jam! 🍓" },
  { q: "Why did the computer go to the doctor?", a: "It had a virus! 💻" },
  { q: "Why did the cookie go to the hospital?", a: "Because it felt crumby! 🍪" },
  { q: "What do you call an alligator in a vest?", a: "An investigator! 🐊" },
  { q: "Why did the golfer bring two pairs of pants?", a: "In case he got a hole in one! ⛳" },
  { q: "Why don't skeletons fight each other?", a: "They don't have the guts! 💀" },
  { q: "What do you call a pig that does karate?", a: "A pork chop! 🐷" },
  { q: "Why was the broom late?", a: "It over-swept! 🧹" },
  { q: "What do you call a bear with no teeth?", a: "A gummy bear! 🐻" },
  { q: "Why did the hipster burn his tongue?", a: "He drank his coffee before it was cool! ☕" },
  { q: "What do you call a lazy kangaroo?", a: "A pouch potato! 🦘" },
  { q: "Why did the fish blush?", a: "Because it saw the ocean's bottom! 🐟" },
  { q: "Why do seagulls fly over the ocean?", a: "Because if they flew over the bay, they'd be bagels! 🥯" },
  { q: "What do you call a factory that makes okay products?", a: "A satisfactory! 🏭" },
  { q: "Why did the clock get kicked out of the library?", a: "It ticked too loud! ⏰" },
  { q: "What do you call a snake that is 3.14 meters long?", a: "A pi-thon! 🐍" },
  { q: "What is a tree's favorite drink?", a: "Root beer! 🍺" },
  { q: "Why did the bee get married?", a: "Because he found his honey! 🐝" },
  { q: "Why do cows wear bells?", a: "Because their horns don't work! 🔔" },
  { q: "What do you call an elephant that doesn't matter?", a: "An irrelephant! 🐘" },
  { q: "Why did the orange stop rolling?", a: "It ran out of juice! 🍊" },
  { q: "What do you call a sheep with no legs?", a: "A cloud! ☁️" },
  { q: "Why did the banana go to the doctor?", a: "It wasn't peeling well! 🍌" },
  { q: "Why are balloon prices rising?", a: "Inflation! 🎈" },
  { q: "What did one plate say to the other?", a: "Tonight, dinner is on me! 🍽️" },
  { q: "Why did the teacher wear sunglasses?", a: "Because her students were so bright! 😎" },
  { q: "What kind of shoes do ninja-cats wear?", a: "Sneakers! 👟🐱" },
  { q: "Why did the stadium get hot after the game?", a: "All the fans left! 🏟️" },
  { q: "What is a cat's favorite color?", a: "Purr-ple! 💜" },
  { q: "Why did the lemon fail its driving test?", a: "It kept peeling out! 🍋" },
  { q: "What do you call a row of rabbits hopping backward?", a: "A receding hare-line! 🐰" },
  { q: "Why do spiders make great web developers?", a: "Because they love finding bugs! 🕷️" },
  { q: "What do you call a turtle that takes up photography?", a: "A snapping turtle! 🐢" },
  { q: "Why did the coffee file a police report?", a: "It got mugged! ☕" },
  { q: "Why did the duck get arrested?", a: "He was caught selling quack! 🦆" },
  { q: "What do you call a horse that lives next door?", a: "A neigh-bor! 🐴" },
  { q: "Why did the astronaut break up with his girlfriend?", a: "He needed space! 🚀" },
  { q: "What do you call a sleeping wolf?", a: "A werewolf (where-is-he-sleeping)! 🐺" },
  { q: "Why did the cheese go to the art museum?", a: "It wanted to see the grate works! 🧀" },
  { q: "What do you call a penguin in the desert?", a: "Lost! 🐧" },
  { q: "Why don't ants get sick?", a: "Because they have tiny little anti-bodies! 🐜" },
  { q: "What do you call an owl that does magic?", a: "Hoodini! 🦉" },
  { q: "Why did the lightbulb go to school?", a: "It wanted to be brighter! 💡" },
  { q: "What is an astronaut's favorite key on the keyboard?", a: "The Space bar! ⌨️" },
  { q: "Why did the boy bring a ladder to school?", a: "To go to high school! 🪜" },
  { q: "What do you call a shoe made out of a banana?", a: "A slipper! 🍌" },
  { q: "Why did the grape stop in the middle of the road?", a: "It ran out of juice! 🍇" },
  { q: "What kind of keys do kids like?", a: "Cookies! 🍪" },
  { q: "Why did the egg hide?", a: "It was a little chicken! 🥚" },
  { q: "What do you call a dog that is cold?", a: "A chili dog! 🌭" },
  { q: "Why did the cow cross the road?", a: "To get to the udder side! 🐄" },
  { q: "What did the big flower say to the little flower?", a: "Hey bud! 🌸" },
  { q: "Why did the melon jump into the lake?", a: "It wanted to be a watermelon! 🍉" },
  { q: "What do you call a pencil with two erasers?", a: "Pointless! ✏️" },
  { q: "Why was the belt arrested?", a: "For holding up a pair of pants! 👖" },
  { q: "Why did the tomato roll down the hill?", a: "It couldn't ketchup! 🍅" },
  { q: "What do you call a line of men waiting for a haircut?", a: "A barberqueue! 💈" },
  { q: "Why did the computer squeak?", a: "Because someone stepped on its mouse! 🖱️" },
  { q: "Why did the tree go to the dentist?", a: "It needed a root canal! 🦷" },
  { q: "What do you call a dynamic music-maker?", a: "A conductor! 🎼" },
  { q: "Why did the bread go to the doctor?", a: "It felt moldy! 🍞" },
  { q: "What is a computer's favorite snack?", a: "Microchips! 🥔" },
  { q: "Why did the scientist install a knocker on his door?", a: "He wanted to win the No-bel prize! 🔔" },
  { q: "What do you call a rich penny?", a: "A cent-sational coin! 🪙" },
  { q: "Why did the jelly go to the party?", a: "It was a jam session! 🍓" },
  { q: "What do you call a snowman in July?", a: "A puddle! ⛄" },
  { q: "Why did the chicken go to the seance?", a: "To cross over to the other side! 🐔" },
  { q: "What is a wizard's favorite subject?", a: "Spelling! 🪄" },
  { q: "Why did the pillow go to the library?", a: "It wanted to get some rest-reading! 🛌" },
  { q: "What do you call a dinosaur with a big vocabulary?", a: "A thesaurus! 🦖" },
  { q: "Why did the developer go broke?", a: "Because he used up all his cache! 💻" },
  { q: "What is a pirate's favorite letter?", a: "You'd think it's R, but it's the C! 🏴‍☠️" },
  { q: "Why did the calendar get nervous?", a: "Its days were numbered! 📅" },
  { q: "What do you call a bear that is caught in the rain?", a: "A drizzly bear! 🐻" },
  { q: "Why did the ocean wave to the shore?", a: "It just wanted to say shore-ly hello! 🌊" }
];
